### ISSUE TITLE
Adjust temperature, presence_penalty, frequency_penalty etc.

### ISSUE THREAD

**Issue by essovius** [FrancescoCoding/easyGPT#9]
Sorry if this is not an issue but I couldn't find how I can adjust temperature, presence_penalty, frequency_penalty etc. for npm_module like [here](https://platform.openai.com/docs/api-reference/chat/create)

**Comment by AdamGovier** [comment]
@essovius We haven't implemented them yet but I will add them by the end of the day. Thank you.

**Comment by AdamGovier** [comment]
Added the options you listed as a start. I will add more further down the line, let me know if there is anymore in particular.

Feel free to contribute an [example](https://github.com/FrancescoCoding/easyGPT/tree/main/npm_module/examples) of presence_penalty & frequency_penalty to the repository. I have added an example of temperature myself. 

Thank you! The documentation has been updated too, if you're stuck.
